[updated] support for multiple x7 devices on osx & linux

diff --git a/language-extensions/vscode/droid-lang/buildscript/sendmidi/linux/sendpatch b/language-extensions/vscode/droid-lang/buildscript/sendmidi/linux/sendpatch
--- a/language-extensions/vscode/droid-lang/buildscript/sendmidi/linux/sendpatch
+++ b/language-extensions/vscode/droid-lang/buildscript/sendmidi/linux/sendpatch
@@ -9,17 +9,15 @@ sed 's/#.*//' $1 >> $TMPFILENAME
 # Write SYSEX end byte
 echo '\0367' >> $TMPFILENAME
 
-
-./sendmidi dev droid syf $TMPFILENAME
+./sendmidi dev "$2" syf $TMPFILENAME
 
 if [ "$?" != 0 ]
 then
-    echo "Error sending MIDI SYSEX message" >&2
+    echo "Error sending MIDI SYSEX message to device $2" >&2
     rm -f $TMPFILENAME
     exit 1
 else
-    echo "Successfully sent $(wc -c < $TMPFILENAME) bytes to DROID X7"
+    echo "Successfully sent $(wc -c < $TMPFILENAME) bytes to device $2"
     rm -f $TMPFILENAME
     exit 0
 fi
-
